################################################################################

default_config:

################################################################################

zeroconf:

################################################################################

lovelace:
  mode: yaml

####################################################
#                                                  #
#                  RESOURCES                       #
#                                                  #
####################################################
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/gauge-card/gauge-card.js
      type: js
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: 'https://fonts.googleapis.com/css?family=Raleway'
      type: css
    - url: /local/mycss.css?v=0.1
      type: css
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: module
      
  dashboards:
    lovelace-mobile-dashboard:
      mode: yaml
      title: Mobile
      filename: mobile-dashboard.yaml
      icon: mdi:cellphone-android
      show_in_sidebar: true
      require_admin: true
    lovelace-tablet-dashboard:
      mode: yaml
      title: Tablet
      filename: tablet-dashboard.yaml
      icon: mdi:tablet-cellphone
      show_in_sidebar: true
      require_admin: true
    lovelace-echo-show-dashboard:
      mode: yaml
      title: Echo
      filename: echo-show-dashboard.yaml
      icon: mdi:amazon-alexa
      show_in_sidebar: true
      require_admin: true
      
################################################################################

frontend:
  themes: !include_dir_merge_named themes
  
###############################   DEFAULT   ####################################
  
homeassistant:
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config
  customize: !include customize.yaml
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: Europe/Rome
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password
  name: Casa
  external_url: !secret http_base_url_ovh
  internal_url: "https://192.168.1.114:8123"

media_source:
  
recorder:
  #purge_interval: 1
  purge_keep_days: 3
  commit_interval: 60
  include:
    domains:
    - sensor
    - climate
    - binary_sensor
  exclude:
    entities:
    - sensor.last_boot
    - sensor.date
    - sensor.time
    - sensor.workday
    - sun.sun

###############################   HTTP   #######################################

http:
#   base_url: !secret http_base_url_ovh
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: False
  login_attempts_threshold: 5

  
################################   IFTTT & REST  #####################################

# ifttt:
#   key: !secret ifttt_key
   
rest_command:
  restart_plex:
    url: 'http://192.168.1.114:1234/plex/restart'
  start_plex:
    url: 'http://192.168.1.114:1234/plex/start'
  stop_plex:
    url: 'http://192.168.1.114:1234/plex/stop'
  update_plex_movies_library:
    url: !secret plex_update_movies_library_url
  update_plex_tvshows_library:
    url: !secret plex_update_tvshows_library_url
  get_image_plex:
    url: 'http://192.168.1.114:1234/plex/get_image'
  play_media:
    url: 'http://192.168.1.114:1234/plex/play_media'
  play_episode:
    url: 'http://192.168.1.114:1234/plex/play_episode'
  reboot_retropie:
    url: 'http://192.168.1.118:1234/retropie/reboot'
  poweroff_retropie:
    url: 'http://192.168.1.118:1234/retropie/poweroff'
  mount_hd:
    url: 'http://192.168.1.114:1234/hassio/pi4/mountHD'
  umount_hd:
    url: 'http://192.168.1.114:1234/hassio/pi4/umountHD'
  reboot_pi4:
    url: 'http://192.168.1.114:1234/hassio/pi4/reboot'
  poweroff_pi4:
    url: 'http://192.168.1.114:1234/hassio/pi4/poweroff'
  mount_wd:
    url: 'http://192.168.1.114:1234/hassio/nas/mount_wd'
  umount_wd:
    url: 'http://192.168.1.114:1234/hassio/nas/umount_wd'
  mount_wd2:
    url: 'http://192.168.1.114:1234/hassio/nas/mount_wd2'
  umount_wd2:
    url: 'http://192.168.1.114:1234/hassio/nas/umount_wd2'
  mount_w3:
    url: 'http://192.168.1.114:1234/hassio/nas/mount_wd3'
  umount_w3:
    url: 'http://192.168.1.114:1234/hassio/nas/umount_wd3'
  mount_toshiba:
    url: 'http://192.168.1.114:1234/hassio/nas/mount_toshiba'
  umount_toshiba:
    url: 'http://192.168.1.114:1234/hassio/nas/umount_toshiba'
  mount_hitachi:
    url: 'http://192.168.1.114:1234/hassio/nas/mount_hitachi'
  umount_hitachi:
    url: 'http://192.168.1.114:1234/hassio/nas/umount_hitachi'

#########################   TELEGRAM   #########################################

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_chat_id_u
notify:
  - name: notifiche_u
    platform: telegram
    chat_id: !secret telegram_chat_id_u
  - platform: alexa_media
    name: alexa_media

################################################################################

automation old: !include_dir_merge_list automations
script : !include_dir_merge_named scripts
group: !include groups.yaml

#############################   ENTITIES   #####################################

climate: !include /config/entities/climate.yaml
input_boolean: !include /config/entities/input_boolean.yaml
input_number: !include /config/entities/input_number.yaml
sensor: !include /config/entities/sensor.yaml
switch: !include /config/entities/switch.yaml
timer: !include /config/entities/timer.yaml
yeelight: !include /config/entities/yeelight.yaml

input_text:
  media_to_play:
    name: Media da riprodurre
    initial: some media
  place_where_play:
    name: Luogo dove riprodurre
    initial: some place
  episode_to_play:
    name: Episodio da riprodurre
    initial: some episode
  season_to_play:
    name: Stagione da riprodurre
    initial: some season
  show_to_play:
    name: Show da riprodurre
    initial: some show
  text1:
    name: Testo annuncio
    initial: Some Text
    
input_select:
  echo_list:
    name: Lista Echo
    options:
      - Umberto
      - Mamma
      - Salotto
    initial: Umberto
    icon: mdi:amazon-alexa
media_player:
  - platform: androidtv
    name: Fire TV Stick
    device_class: firetv
    host: 192.168.1.116
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037
#########################   DISCOVERY   ########################################

# discovery:
#   ignore:
#     - yeelight
#     - xiaomi_gw

light:
  - platform: mqtt
    name: "Luce bagno"
    state_topic: "shellies/shelly1-7703E4/relay/0"
    command_topic: "shellies/shelly1-7703E4/relay/0/command"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "Luce camera"
    state_topic: "shellies/shelly1-55DFE4/relay/0"
    command_topic: "shellies/shelly1-55DFE4/relay/0/command"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    retain: false
  - platform: mqtt
    name: "Luce scale"
    state_topic: "shellies/shelly1-76F7D1/relay/0"
    command_topic: "shellies/shelly1-76F7D1/relay/0/command"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    retain: false

api:
alexa: !include /config/entities/alexa.yaml

sensor places_umberto:
  - platform: places
    name: Redmi Umberto
    devicetracker_id: device_tracker.redmi_5_plus
    options: zone,place
    map_provider: google
    map_zoom: 19
    home_zone: zone.home
    api_key: !secret email

proximity:
  home:
    devices:
      - device_tracker.redmi_5_plus
    tolerance: 50
    unit_of_measurement: km
  lavoro:
    zone: Lavoro
    devices:
      - device_tracker.redmi_5_plus
    tolerance: 10
    unit_of_measurement: m
